# Generated by Django 3.2.6 on 2021-10-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enlighten_Minds', '0003_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='goals_achieved_by_this_course',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='reson_for_applying',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='students_affordable_money',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='students_affordable_money_reason',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
