# Generated by Django 3.2.6 on 2021-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enlighten_Minds', '0004_auto_20211009_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='annual_income',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='educational_background',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='emplypment_status',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
